
#load the function into the current session
. T:\Lesson_25\Get-FolderSize-v3.ps1

#get the function definition which is a scriptblock
$sb = (get-item Function:\Get-FolderSize).scriptblock

#invoke the command remotely using the previously created
#pssession

$data = Invoke-Command -Session $FP -ScriptBlock $sb -ArgumentList C:\shares

<#raw results

$data

#formatted data
$data | Select Fullname,Count,
@{Name="SizeMB";Expression={[math]::Round($_.size/1mb,2)}}

#>

#turn this into an HTML report
$paramHash = @{
Title = "CHI-FP01 Share Report"
CSSuri = "\\CHI-FP01\IT\sample.css"
PreContent = "<H2>CHI-FP01 Shared Folder Usage</H2>"
PostContent = "<br><I>generated by $env:userdomain\$env:username</I>"
}

$data | Select Fullname,Count,
@{Name="SizeMB";Expression={[math]::Round($_.size/1mb,2)}} |
ConvertTo-Html @paramhash | 
Out-File c:\work\FP01Usage.htm -Encoding ascii

invoke-item c:\work\fp01Usage.htm
