# Module manifest for module 'tflhelp'
# Generated by: TFL
# Generated on: 09/03/2012
@{
# Script module or binary module file associated with this manifest
RootModule            = 'TFLHelp.psm1'

# Module documentation
ModuleVersion          = '1.0'
GUID                   =  '05cb0e09-bf6d-4c2f-83c5-d02de963307a'
Author                 = 'Thomas Lee - DoctorDNS@Gmail.Com'
Description            = 'Demonstrates extensible help'

DotNetFrameworkVersion = '4.0'
PowerShellVersion      = '3.0'

# Functions to export from this module
FunctionsToExport = '*'

# List of all files packaged with this module
FileList = 'en-US\about_tflhelp.help.txt'

# Scripts To Process
ScriptsToProcess = 'Get-TFLHelp.ps1','Remove-TFLHelp.ps1'

# HelpInfo URI of this module
HelpInfoURI = 'http://cookham1.cookham.net/tflhelp'

}

